### PR TITLE
Update really all modules

### PR DESCRIPTION
**Pull request by binarykitchen**
Here you go, a small PR to make sure this grunt plugin is compatible with the latest bunyan version.

### CODE REVIEW

**Comment by pwmckenna** [comment]
awesome! thanks for the update :beers:

**Comment by pwmckenna** [comment]
just published version 0.4.3 with this patch. thanks again

**Comment by binarykitchen** [comment]
My pleasure. Just realised that I should have bumped to 0.4.2 instead but never mind. All good now. Thx for the quick release.

**Comment by pwmckenna** [comment]
oh, totally missed your version bump...too lazy to create the tags myself though, always use `npm version patch`

**Pull request merged**
